# Generated by Django 3.2.10 on 2021-12-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.FilePathField(verbose_name='Image file')),
                ('recipe_file', models.FilePathField(verbose_name='Recipe file')),
                ('_ingredients', models.TextField(verbose_name='Ingredients')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
