# Generated by Django 3.2.10 on 2021-12-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeGroup',
            fields=[
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('views', models.IntegerField(default=0, verbose_name='Views count')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views count'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.recipegroup', verbose_name='Group'),
        ),
    ]
