# Generated by Django 3.2.10 on 2021-12-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211224_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='group',
        ),
        migrations.AddField(
            model_name='recipe',
            name='groups',
            field=models.ManyToManyField(null=True, to='recipes.RecipeGroup', verbose_name='Group'),
        ),
    ]
