# Generated by Django 3.2.10 on 2022-02-11 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211225_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipegroup',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
    ]
