# Generated by Django 3.2.10 on 2022-06-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipegroup_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preview_file',
            field=models.FilePathField(default='', verbose_name='Preview file'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_file',
            field=models.FilePathField(default='', verbose_name='Image file'),
        ),
    ]
