# Generated by Django 3.2.10 on 2021-12-25 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211225_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='image_file',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='views',
        ),
        migrations.RemoveField(
            model_name='recipegroup',
            name='views',
        ),
        migrations.AddField(
            model_name='recipe',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='groups',
            field=models.ManyToManyField(to='recipes.RecipeGroup', verbose_name='Group'),
        ),
    ]
