
RECIPES_DATA_OUTPUT_PATH = 'recipes'
RECIPES_OUTPUT_PATH = '.'

RECIPES_LIST_ID = 'card-list_2-0'
RECIPES_LIST_RECIPE_CLASS = 'card-list__item'
RECIPES_LIST_RECIPE_TITLE_CLASS = 'card__title'
RECIPES_LIST_RECIPE_LINK_CLASS = 'card'
RECIPES_LIST_RECIPE_IMAGE_CLASS = 'card__image'


RECIPE_DESCRIPTION_ELEMENT_TITLE_CLASS = 'mntl-sc-block-heading__text'
RECIPE_DESCRIPTION_FILTER_CLASS = 'link-list__link'
